### ISSUE TITLE
Unable to install package in Python from git

### ISSUE THREAD

**Issue by coolshreysh1000** [Dagalon/PyStochasticVolatility#1]
I tried the below command in my CMD:
`pip install git+https://github.com/Dagalon/PyStochasticVolatility.git#egg=PyStochasticVolatility`

But it showing the below error:
` error: package directory 'MC_Engines\MC_Bergomi2F' does not exist`

Please suggest some ideas to get around this issue.

I have also downloaded zip archive of this repo and tried `python setup.py build` but that is also showing same error.

**Comment by Dagalon** [comment]
Hello,
Firstly thank you so much for your interest in this repository. Basically, the error you have reported has been fixed. If you download again the code you must be able to run the setup.py.

**Comment by coolshreysh1000** [comment]
Thanks. I can now install it successfully.
