### ISSUE TITLE
Name of the Book (& Edition) which has been referred for the examples folder

### ISSUE THREAD

**Issue by Starlord2222** [Dagalon/PyStochasticVolatility#2]
I just wanted to know which book (and which edition of the book) it is referring for the examples folder: https://github.com/Dagalon/PyStochasticVolatility/tree/master/Examples ?? Help regarding this will be really appreciated. Thank You!

**Comment by MerinoRaul** [comment]
Hello

The book is:

https://www.amazon.es/Malliavin-Calculus-Finance-Financial-Mathematics/dp/0367893444

Best,

Raul

**Comment by Starlord2222** [comment]
Thank You!
